import js from '@eslint/js'
import globals from 'globals'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

export default [
  { ignores: ['dist', 'node_modules', '*.config.js'] },
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: {
        ...globals.browser,
        ...globals.node
      },
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    settings: { 
      react: { version: '18.3' },
      'import/resolver': {
        node: {
          extensions: ['.js', '.jsx']
        }
      }
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // Base recommended rules
      ...js.configs.recommended.rules,
      
      // React recommended rules
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      ...reactHooks.configs.recommended.rules,
      
      // Custom rules
      'react/jsx-no-target-blank': 'off',
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react': 'off',
      'react/jsx-uses-vars': 'error',
      'react/jsx-key': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-undef': 'error',
      'react/no-array-index-key': 'warn',
      'react/no-unescaped-entities': 'off',
      
      // React Hooks rules
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      
      // React Refresh rules
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      
      // General code quality rules
      'no-console': 'warn',
      'no-debugger': 'error',
      'no-unused-vars': 'warn',
      'no-undef': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-multiple-empty-lines': ['error', { max: 2 }],
      'eol-last': 'error',
      'comma-dangle': ['error', 'never'],
      'semi': ['error', 'always'],
      'quotes': ['error', 'single', { avoidEscape: true }],
      'indent': ['error', 2],
      'object-curly-spacing': ['error', 'always'],
      'array-bracket-spacing': ['error', 'never'],
      'comma-spacing': ['error', { before: false, after: true }],
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'keyword-spacing': 'error',
      'arrow-spacing': 'error',
      'template-curly-spacing': 'error',
      'block-spacing': 'error',
      'computed-property-spacing': 'error',
      'func-call-spacing': 'error',
      'rest-spread-spacing': 'error',
      'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      'operator-linebreak': ['error', 'before'],
      'function-paren-newline': ['error', 'consistent'],
      'array-element-newline': ['error', 'consistent'],
      'object-curly-newline': ['error', { consistent: true }],
      'no-trailing-spaces': 'error',
      'no-multi-spaces': 'error',
      'no-irregular-whitespace': 'error',
      'max-len': ['warn', { code: 100, ignoreUrls: true, ignoreStrings: true }],
      'camelcase': ['error', { properties: 'never' }],
      'new-cap': 'error',
      'no-new-object': 'error',
      'no-array-constructor': 'error',
      'prefer-template': 'error',
      'template-curly-spacing': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'no-confusing-arrow': 'error',
      'no-useless-constructor': 'error',
      'no-dupe-class-members': 'error',
      'no-duplicate-imports': 'error',
      'no-useless-rename': 'error',
      'object-shorthand': 'error',
      'prefer-destructuring': ['error', { object: true, array: false }],
      'prefer-spread': 'error',
      'prefer-rest-params': 'error',
      'no-useless-escape': 'error',
      'no-useless-concat': 'error',
      'prefer-template': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-return-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-useless-call': 'error',
      'no-useless-return': 'error',
      'radix': 'error',
      'yoda': 'error',
      'eqeqeq': 'error',
      'curly': ['error', 'all'],
      'default-case': 'error',
      'no-empty': 'error',
      'no-empty-function': 'error',
      'no-fallthrough': 'error',
      'no-redeclare': 'error',
      'no-unused-labels': 'error',
      'no-useless-catch': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-extra-semi': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-loop-func': 'error',
      'no-magic-numbers': ['warn', { ignore: [-1, 0, 1, 2] }],
      'no-new': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-await': 'error',
      'no-self-assign': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unused-expressions': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'prefer-promise-reject-errors': 'error',
      'require-await': 'error',
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      'yield-star-spacing': 'error',
      'init-declarations': 'error',
      'no-catch-shadow': 'error',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-restricted-globals': 'error',
      'no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef-init': 'error',
      'no-use-before-define': 'error',
      'array-bracket-newline': ['error', 'consistent'],
      'array-element-newline': ['error', 'consistent'],
      'block-spacing': 'error',
      'brace-style': 'error',
      'camelcase': ['error', { properties: 'never' }],
      'capitalized-comments': 'off',
      'comma-dangle': ['error', 'never'],
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': 'error',
      'consistent-this': 'error',
      'eol-last': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'error',
      'func-names': 'off',
      'func-style': 'off',
      'function-paren-newline': ['error', 'consistent'],
      'id-blacklist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'implicit-arrow-linebreak': 'error',
      'indent': ['error', 2],
      'indent-legacy': 'off',
      'jsx-quotes': 'error',
      'key-spacing': 'error',
      'keyword-spacing': 'error',
      'line-comment-position': 'off',
      'linebreak-style': 'error',
      'lines-around-comment': 'off',
      'lines-around-directive': 'error',
      'max-depth': 'off',
      'max-len': ['warn', { code: 100, ignoreUrls: true, ignoreStrings: true }],
      'max-lines': 'off',
      'max-nested-callbacks': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'max-statements-per-line': 'off',
      'multiline-comment-style': 'off',
      'multiline-ternary': 'off',
      'new-cap': 'error',
      'new-parens': 'error',
      'newline-after-var': 'off',
      'newline-before-return': 'off',
      'newline-per-chained-call': 'off',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-continue': 'off',
      'no-inline-comments': 'off',
      'no-lonely-if': 'error',
      'no-mixed-operators': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': ['error', { max: 2 }],
      'no-negated-condition': 'off',
      'no-nested-ternary': 'error',
      'no-new-object': 'error',
      'no-plusplus': 'off',
      'no-restricted-syntax': 'off',
      'no-tabs': 'error',
      'no-ternary': 'off',
      'no-trailing-spaces': 'error',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': 'error',
      'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
      'one-var': 'off',
      'one-var-declaration-per-line': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': ['error', 'before'],
      'padded-blocks': 'off',
      'padding-line-between-statements': 'off',
      'prefer-object-spread': 'error',
      'quote-props': 'off',
      'quotes': ['error', 'single', { avoidEscape: true }],
      'require-jsdoc': 'off',
      'semi': ['error', 'always'],
      'semi-spacing': 'error',
      'semi-style': 'error',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'never'],
      'space-in-parens': 'error',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': 'off',
      'switch-colon-spacing': 'error',
      'template-tag-spacing': 'error',
      'unicode-bom': 'error',
      'wrap-regex': 'off'
    },
  },
]
